# Generated by Django 5.2 on 2025-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('lugar_nacimiento_distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('lugar_nacimiento_provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('lugar_nacimiento_departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('tutor_apellidos', models.CharField(blank=True, max_length=100)),
                ('tutor_nombres', models.CharField(blank=True, max_length=100)),
                ('tutor_parentesco', models.CharField(blank=True, max_length=100)),
                ('nombre_ies', models.CharField(max_length=100)),
                ('tipo_institucion', models.CharField(choices=[('Publica', 'Publica'), ('Privada', 'Privada')], max_length=20)),
                ('anio_egreso', models.CharField(max_length=4, verbose_name='Año_egreso')),
                ('direccion_institucion', models.CharField(max_length=255)),
                ('institucion_distrito', models.CharField(max_length=100)),
                ('institucion_provincia', models.CharField(max_length=100)),
                ('institucion_departamento', models.CharField(max_length=100)),
                ('programa_postula_primera_opcion', models.CharField(choices=[('C', 'Contabilidad'), ('EM', 'Explotación Minera'), ('CC', 'Construcción Civil')], max_length=2)),
                ('programa_postula_segunda_opcion', models.CharField(choices=[('C', 'Contabilidad'), ('EM', 'Explotación Minera'), ('CC', 'Construcción Civil')], max_length=2)),
                ('enterado_proceso_admision', models.CharField(max_length=100, verbose_name='¿Cómo se entero del proceso de admisión?')),
                ('codigo_voucher', models.CharField(max_length=15, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('voucher_codigo', models.CharField(max_length=50)),
                ('dni_file', models.FileField(upload_to='postulantes/dni/')),
                ('certificado_file', models.FileField(upload_to='postulantes/certificado/')),
                ('recibo_file', models.FileField(upload_to='postulantes/recibo/')),
            ],
        ),
    ]
