# Generated by Django 5.2 on 2025-04-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='voucher_codigo',
        ),
    ]
