# Generated by Django 5.2 on 2025-04-03 21:09

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_remove_postulante_voucher_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='certificado_file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='postulantes/certificado/'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='dni_file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='postulantes/dni/'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='recibo_file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='postulantes/recibo/'),
        ),
    ]
